server:
  port: 85
---
eureka:
  client:
    service-url:
      defaultzone : http://127.0.0.1:8761/eureka
---
spring:
  application:
    name: hystrix-cli
    
    
feign:
  hystrix:
    enabled: true