server:
  port: 8082
spring:
  application:
    name: sample-sca2
  cloud:
    nacos:
      discovery:
        server-addr: 106.13.201.243:8848
        group: DEFAULT_GROUP
    sentinel:
      transport:
        port: 8719
        dashboard: 106.13.201.243:8080
feign:
  sentinel:
    enabled: true
