server:
  port: 8088

spring:
  application:
    name: gateway-sample
  redis:
    host: 106.13.201.243
    port: 6379
  cloud:
      nacos:
        discovery:
          server-addr: 106.13.201.243:8848
          group: DEFAULT_GROUP
      sentinel:
        transport:
          port: 8719
          dashboard: 106.13.201.243:8080
      gateway:
        discovery:
          locator:
            lower-case-service-id: true
            enabled: true
        routes:
          - id: host_route
            uri: lb://sample-sca
            predicates:
              - Path=/sca/**  #/hello/{name}
#            filters:
#              - StripPrefix=1

logging:
  level:
     org.springframework.cloud.gateway: debug
